#ifndef SIMBAD_CORE_FWD_PROPERTIES_FWD_HPP
#define SIMBAD_CORE_FWD_PROPERTIES_FWD_HPP

#include "core_def.hpp"
BEGIN_NAMESPACE_CORE
class property_tree;
END_NAMESPACE_CORE

#endif //SIMBAD_PROPERTIES_FWD_HPP
