
image: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_58_0

clone_folder: c:\SimBaD

platform: x64
configuration: Release

before_build:
  - echo Running cmake...
  - cd c:\SimBaD
  - cmake -G "Visual Studio 14 2015 Win64"
  

build_script:
  - cmake --build . --target all