
image: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_58_0
  BOOST_LIBRARYDIR_WIN32: C:\Libraries\boost_1_58_0\lib32-msvc-12.0
  BOOST_LIBRARYDIR_WIN64: C:\Libraries\boost_1_58_0\lib64-msvc-12.0

platform: x64
configuration: Release

branches:
  except:
    - gh-pages

clone_folder: c:\SimBaD

before_build:
  - cmd: cd C:\SimBaD
  - cmd: md build
  - cmd: cd build
  # We generate project files for Visual Studio 12 because the boost binaries installed on the test server are for Visual Studio 12.
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64  
  - cmd: if "%platform%"=="Win32" set BOOST_LIBRARYDIR=%BOOST_LIBRARYDIR_WIN32%
  - cmd: if "%platform%"=="x64"   set BOOST_LIBRARYDIR=%BOOST_LIBRARYDIR_WIN64%
  - cmd: dir %BOOST_ROOT%
  - cmd: dir %BOOST_LIBRARYDIR%
  - cmd: dir C:\Libraries\boost_1_62_0
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON" ..
  

build_script:
  - cmake --build . --target all