
image: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_62_0
  BOOST_LIBRARYDIR_WIN32: C:\Libraries\boost_1_62_0\lib32-msvc-14.0
  BOOST_LIBRARYDIR_WIN64: C:\Libraries\boost_1_62_0\lib64-msvc-14.0

platform: x64
  
configuration: 
  - Debug
  - Release

branches:
  except:
    - gh-pages

clone_folder: c:\SimBaD

before_build:
  - cmd: cd C:\SimBaD
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64  
  - cmd: if "%platform%"=="Win32" set BOOST_LIBRARYDIR=%BOOST_LIBRARYDIR_WIN32%
  - cmd: if "%platform%"=="x64"   set BOOST_LIBRARYDIR=%BOOST_LIBRARYDIR_WIN64%
#  - cmd: dir %BOOST_LIBRARYDIR%
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..

  

build:
  project: C:\SimBaD\build\ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal

test_script:
  - ctest -C %configuration% --VV --output-on-failure

matrix:
  fast_finish: true

after_build:
  - cmd: dir %APPVEYOR_BUILD_FOLDER%
  - cmd: 7z a SimBaD.zip %APPVEYOR_BUILD_FOLDER%\build\cli\%configuration%\cli.exe %APPVEYOR_BUILD_FOLDER%\examples\ 

artifacts:
  path: SimBad.zip
  name: Binary
  