
image: Visual Studio 2017

environment:
  BOOST_ROOT: C:\Libraries\boost_1_62_0
  BOOST_LIBRARYDIR_WIN32: C:\Libraries\boost_1_62_0\lib32-msvc-15.0
  BOOST_LIBRARYDIR_WIN64: C:\Libraries\boost_1_62_0\lib64-msvc-15.0
  INSTALL_DIR: c:\SimBaD\install

platform: x64
  
configuration: 
  - Debug
  - Release

branches:
  except:
    - gh-pages

clone_folder: c:\SimBaD

before_build:
  - cmd: cd C:\SimBaD
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 15 2017
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 15 2017 Win64  
  - cmd: if "%platform%"=="Win32" set BOOST_LIBRARYDIR=%BOOST_LIBRARYDIR_WIN32%
  - cmd: if "%platform%"=="x64"   set BOOST_LIBRARYDIR=%BOOST_LIBRARYDIR_WIN64%
#  - cmd: dir %BOOST_LIBRARYDIR%
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DCMAKE_INSTALL_PREFIX="%INSTALL_DIR%" ../src

  

build:
  project: C:\SimBaD\build\ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal

test_script:
  - ctest -C %configuration% --VV --output-on-failure

matrix:
  fast_finish: true

after_build:
  - cmd: dir %APPVEYOR_BUILD_FOLDER%
  - cmd: cmake --build . --config %configuration% --target install
  - cmd: dir %INSTALL_DIR%
  - cmd: 7z a SimBaD.zip %INSTALL_DIR%

artifacts:
  path: build\SimBaD.zip
  name: Binary
  
