language: cpp

sudo: required
dist: trusty

compiler:
  - clang
      
before_script:
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.9 main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get -y remove llvm-3.4
  - sudo apt-get install clang-3.9 lldb-3.9 libc++-dev libboost-all-dev
env: COMPILER=clang++-3.9 
  
script:
  - mkdir build
  - cd build
  - cmake .. && make