language: generic

matrix:
  include:
    - dist: trusty
      sudo: required
      services:
        - docker
      script:
        - docker -v
        - docker pull $DOCKERIMAGE
        - docker run -v ${PWD}/:/code $DOCKERIMAGE sh -c "mkdir -p /code/build && cd /code/build && cmake ../src -DCMAKE_BUILD_TYPE=Debug && make -j 2"
        - docker run -v ${PWD}/:/code $DOCKERIMAGE sh -c "cd /code/build && ctest --VV -output-on-failure"
      env: DOCKERIMAGE=tozanski/simbad-dev:clang39
    - dist: trusty
      sudo: required
      services:
        - docker
      script:
        - docker -v
        - docker pull $DOCKERIMAGE
        - docker run -v ${PWD}/:/code $DOCKERIMAGE sh -c "mkdir -p /code/build && cd /code/build && cmake ../src -DCMAKE_BUILD_TYPE=Debug && make -j 2"
        - docker run -v ${PWD}/:/code $DOCKERIMAGE sh -c "cd /code/build && ctest --VV -output-on-failure"
      env: DOCKERIMAGE=tozanski/simbad-dev:gcc6  
    - os: osx
      osx_image: xcode7.3
      script:
        - mkdir build && cd build
        - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
        - make -j 2
        - ctest --VV --output-onfailure
      env: COMPILER=clang++
    - dist: trusty
      sudo: required
      services:
        - docker
      script:
        - docker -v
        - docker pull $DEVIMAGE
        - docker run -v ${PWD}/:/code $DEVIMAGE sh -c "mkdir -p /code/build-release && cd /code/build-release && cmake ../src -DCMAKE_BUILD_TYPE=Release && make -j 2"
        - docker run -v ${PWD}/:/code $DEVIMAGE sh -c "cd /code/build-release && ctest --VV -output-on-failure"
        - docker build -f docker/simbad.Dockerfile . -t $OUTIMAGE
      env: 
        - DEVIMAGE=tozanski/simbad-dev:clang
        - OUTIMAGE=tozanski/simbad
        

            
#before_script:
#  - mkdir build
#  - cd build
#  - $COMPILER -v
  
#script:
#  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make -j 2 && ctest --VV --output-on-failure
  
notifications:
  email:
    recipients:
      - secure: "F0C5a1KsXGDgX7ylsgXJj8v7EWSrJuJyX5yEiEFwJt5iXv7Oc3UYX7SOarUA7slD+ywe66q+ZmnCLjwOqu8FEW47T8orCyL4Cko7gCqC0k+oyw1/7ji819p7k2oOUJ2NS8DO8olOqbJUZ02gq37efWP47wm5M7b+jGw3MoJUGWfX7am5aeSVxzEizQeSRnIU/nryh6oSwIjVFzIjDG3DNKTHAl09cEO1RjJYH9iY3w8pcGAVUvxrp8G41Wf2uw6lixM6hMSR3IKPhiWM+wfN+TJDjeN+sAgT4NWt/fUPgkjoGZS7BgOczDxIH5jDPC2qvtcdQQIuVDJlBjSJefqhcmDwkaI/WC3u3arocFnLYcTR/ZyPthlZBAQK0mvLQ27fcU8/4vjwokfVuccLq3nmVOK0A3nR0Mj92MOwwYk/ssU07HcRl6/PenaQAClOF/n5vLMANdM95UbLEkaMxy9Y75gKuX26MqG/7Pjx7YLZedYDePlt0ZjYry7niVeV6HO91TcAeqex+hWAotK9dr2cxD6YnwKJ5RwfTuPsUE3UR3R9HfoIAU8aNUUS5rkrr6QyigmjEFkDMLONC3kY4EyYaSaYL8ISTdc3tYbSz2b1Lev9MhVF1fGFyIqTfhVWun+6lS90r1lEtZo96nTgsYEN/56vQ97JtgYKwQjyT+SqJXQ="
    on_success: always 
    on_failure: always
      
